apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-booking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-booking-app
  template:
    metadata:
      labels:
        app: movie-booking-app
    spec:
      containers:
      - name: movie-booking-app
        image: thetrickuser/movie-app-frontend:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: movie-booking-app
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: movie-booking-app
